### ISSUE TITLE
No output is displayed

### ISSUE THREAD

**Issue by biranchi2018** [rajeshpachaikani/face-detection-opencv-js#1]
I have download the files on my MacOS

![Screenshot 2019-08-18 at 7 14 01 AM](https://user-images.githubusercontent.com/191425/63218178-f2d06480-c187-11e9-8174-96c53680f19f.png)

I followed the instructions and started the http server as below

$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [18/Aug/2019 07:09:52] code 404, message File not found
127.0.0.1 - - [18/Aug/2019 07:09:52] "GET /) HTTP/1.1" 404 -
127.0.0.1 - - [18/Aug/2019 07:09:53] code 404, message File not found
127.0.0.1 - - [18/Aug/2019 07:09:53] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Aug/2019 07:09:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Aug/2019 07:09:56] "GET /js/opencv.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Aug/2019 07:09:56] "GET /js/utils.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Aug/2019 07:11:03] "GET / HTTP/1.1" 200 -

But i am getting the below error in the browser:

![Screenshot 2019-08-18 at 7 12 21 AM](https://user-images.githubusercontent.com/191425/63218181-067bcb00-c188-11e9-993c-1ada2db8abdd.png)

**Comment by rajeshpachaikani** [comment]
Sorry for the late reply. Can you tell me the browser you are using and whether you allowed camera usage when the browser prompt for it?
